AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0.6

# Relax documentation requirements
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  
# Increase method length limits
Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'lib/vector_mcp/browser/**/*'
    - 'examples/**/*'
    - 'spec/**/*'

# Increase ABC size limits
Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'lib/vector_mcp/browser/**/*'
    - 'examples/**/*'
    - 'spec/**/*'

# Increase class length limits
Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'lib/vector_mcp/transport/sse.rb'
    - 'lib/vector_mcp/browser/**/*'
    - 'examples/**/*'

# Increase module length limits
Metrics/ModuleLength:
  Max: 300

# Increase line length
Layout/LineLength:
  Max: 150

# Increase cyclomatic complexity
Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/vector_mcp/browser/**/*'
    - 'examples/**/*'

# Increase perceived complexity
Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/vector_mcp/browser/**/*'
    - 'examples/**/*'

# If you're using RSpec and Rake, you might want to include these extensions
plugins:
  - rubocop-rake

# Ignore long blocks in tests and examples
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'examples/**/*'
    - '*.gemspec'

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'
  
Lint/EmptyClass:
  Enabled: false
