AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

# Relax documentation requirements
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  
# Increase method length limits
Metrics/MethodLength:
  Max: 30

# Increase ABC size limits
Metrics/AbcSize:
  Max: 30

# Increase class length limits
Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'lib/vector_mcp/transport/sse.rb'

# Increase module length limits
Metrics/ModuleLength:
  Max: 250

# Increase line length
Layout/LineLength:
  Max: 150

# Increase cyclomatic complexity
Metrics/CyclomaticComplexity:
  Max: 10

# Increase perceived complexity
Metrics/PerceivedComplexity:
  Max: 10

# If you're using RSpec and Rake, you might want to include these extensions
require:
  - rubocop-rake

# Ignore long blocks in tests
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockChain:
  Exclude:
    - 'spec/**/*'
  
Lint/EmptyClass:
  Enabled: false
